filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/zabbix/zabbix_server.log
    - /var/log/nginx/access.log
    - /var/log/nginx/error.log
    - /var/log/mysql/mysql.log
    - /var/log/messages
    - /var/log/secure

output.logstash:
  hosts: ["localhost:5044"]

setup.ilm.enabled: false
setup.template.enabled: false

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644